name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.1
        version: 1
