name: Phpstan tests

on: ["push", "pull_request"]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3
          php_extensions: bcmath intl gd exif xdebug

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 7.3
          php_extensions: bcmath intl gd exif

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v2
        with:
          php_version: 7.3
          configuration: phpstan.neon
          path: src/
