name: Unit tests

on: ["push", "pull_request"]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3
          php_extensions: bcmath intl gd exif xdebug

      - name: clear cache
        run: php -d memory_limit=-1 ./tests/Application/bin/console ca:cl -e test

      - name: phpunit
        run: php ./vendor/bin/phpunit
